version: "3.7"

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure
    logging:
      options:
        max-size: "20m"
        max-file: "10"

  pgadmin:
    image: dpage/pgadmin4:${TAG-latest}
    depends_on:
      - db
    env_file:
      - .env


  backend-fastapi-project:
    image: 'backend-fastapi-project:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: ./backend/fastapi-project

  
  frontend-vitepress-docs:
    image: 'frontend-vitepress-docs:${TAG-latest}'
    build:
      context: ./frontend/vitepress-docs
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

  frontend-next-client:
    image: 'frontend-next-client:${TAG-latest}'
    build:
      context: ./frontend/next-client
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}
  # frontend-react-dashboard:
  #   image: 'frontend-react-dashboard:${TAG-latest}'
  #   build:
  #     context: ./frontend/react-dashboard


  # queue:
  #   image: rabbitmq:3
  # flower:
  #   image: mher/flower:0.9.7


  # celeryworker:
  #   image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'

volumes:
  db-data:

    # networks:
    #   traefik-public:
    #     # Allow setting it to false for testing
    #     external: ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}
