version: "3.3"

services:

  # proxy:
  #   image: traefik:v2.2
  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: andrew@vibe.us
      PGADMIN_DEFAULT_PASSWORD: 123456
    env_file:
      - .env

  # queue:
  #   image: rabbitmq:3
  # flower:
  #   image: mher/flower:0.9.7
  
  # fast-backend:
  #   image: 'fast-backend:${TAG-latest}'
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./.env
  #   environment:
  #     - POSTGRES_HOST=${POSTGRES_HOST}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   build:
  #     context: ./backend/fastapi_project
  #     dockerfile: Dockerfile
  #     args:
  #       INSTALL_DEV: ${INSTALL_DEV-false}
   
  # celeryworker:
  #   image: '${DOCKER_IMAGE_CELERYWORKER?Variable not set}:${TAG-latest}'
 
  vitepress-docs:
    image: 'vitepress-docs:${TAG-latest}'
    build:
      context: ./frontend/vitepress-docs
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}

  frontend-client:
    image: 'frontend-client:${TAG-latest}'
    build:
      context: ./frontend/next-client
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}
 
  # frontend-dashboard:
  #   image: 'frontend-dashboard:${TAG-latest}'
  #   build:
  #     context: ./frontend/react-dashboard
 
volumes:
  app-db-data:

# networks:
#   traefik-public:
#     # Allow setting it to false for testing
#     external: ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}