name: 'dbt_project'

config-version: 2
version: '0.1'

profile: 'vibe_cdp_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbt_project:
    materialized: table
    +persist_docs:
      relation: true 
      columns: true
    staging:
      materialized: table
      
seeds:
  dbt_project:
    schema: raw
    