vibe_cdp_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 2
      host: 127.0.0.1
      port: 5432
      user: codzr
      password: "140937"
      dbname: vibe_dbt
      schema: dbt
