vibe_cdp_profile:
  target: prod
  outputs:
    dev:
      type: postgres
      threads: 2
      host: 127.0.0.1
      port: 5432
      user: codzr
      password: "140937"
      dbname: vibe_dbt_dev
      schema: dev
    prod:
      type: postgres
      threads: 2
      host: 127.0.0.1
      port: 5432
      user: codzr
      password: "140937"
      dbname: vibe_dbt_dev
      schema: public
