name: Lint Models

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"

      - name: Install SQLFluff
        run: "pip install sqlfluff==2.3.2"

      - name: Lint models
        run: "sqlfluff lint models --dialect ansi"
